BEGIN;

DROP POLICY IF EXISTS tenant_isolation ON labels;
ALTER TABLE IF EXISTS labels DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON quick_replies;
ALTER TABLE IF EXISTS quick_replies DISABLE ROW LEVEL SECURITY;

COMMIT;
